// src/lib/components/UploadFilePreview.svelte
<script lang="ts">
	import { formatBytes } from '$lib/formating';
	import type { FileUpload } from '$lib/upload.svelte';
	import ProgressBar from '$lib/components/ProgressBar.svelte';

	type Props = {
		file: File;
		upload?: FileUpload;
		remove: () => void;
	};

	let { file, upload, remove }: Props = $props();

	let suffix = $derived.by(() => {
		const parts = file.name.split('.');
		if (parts.length < 2) return;

		return parts[parts.length - 1].toUpperCase();
	});

	let fileSize = $derived(formatBytes(file.size));
</script>

<div class="flex flex-col gap-2">
	<div class="flex items-center justify-between">
		<div class="flex flex-col gap-1">
			<div class="text-lg font-semibold">{file.name}</div>
			<div class="flex gap-2">
				<div
					class="bg-blue-2 border-blue-3 text-blue-6 rounded-md border px-1.5 py-0.5 text-sm font-semibold"
				>
					{fileSize}
				</div>
				{#if suffix}
					<div
						class="bg-blue-2 border-blue-3 text-blue-6 rounded-md border px-1.5 py-0.5 text-sm font-semibold"
					>
						{suffix}
					</div>
				{/if}
			</div>
		</div>

		<button type="button" onclick={remove} class="rounded bg-black px-2 py-1 font-medium text-white"
			>delete</button
		>
	</div>

	{#if upload}
		<ProgressBar progress={upload.progress} />
	{/if}
</div>

// old/src/components/UploadFilePreview.vue
<template>
	<li class="flex items-center gap-4 w-full">
		<div class="grid flex-1">
			<div class="font-bold whitespace-nowrap truncate overflow-hidden">
				{{ task.name }}
			</div>

			<div class="flex items-center h-6">
				<ProgressBar v-if="task.status !== 'success'" :progress="task.progress" />
				<div v-if="task.status === 'success'" class="font-semibold opacity-80 text-sm">
					{{ size }} <span v-if="task.type">● {{ task.type.toUpperCase() }}</span>
				</div>
			</div>
		</div>

		<button
			class="flex items-center justify-end w-8 h-full"
			@click="emit('remove', task)"
		>
			<div
				class="i-material-symbols-cancel-outline-rounded text-xl hover:text-red-500 transition-all"
			></div>
		</button>
	</li>
</template>

<script setup lang="ts">
import { formatBytes } from '../helpers/helpers';
import { UploadTask } from '../types';

const { task } = defineProps<{ task: UploadTask }>();

const emit = defineEmits<{
	(event: 'remove', value: UploadTask): void;
}>();

const size = computed(() => formatBytes(task.size));
</script>
